CREATE TABLE custom_metadata (
	state_code varchar(2) NOT NULL,
	asmt_custom_metadata longtext
);
CREATE TABLE dim_asmt (
	asmt_rec_id bigint NOT NULL,
	asmt_guid varchar(255) NOT NULL,
	asmt_type varchar(32) NOT NULL,
	asmt_period varchar(32),
	asmt_period_year int NOT NULL,
	asmt_version varchar(40) NOT NULL,
	asmt_subject varchar(64) NOT NULL,
	effective_date varchar(8) NOT NULL,
	asmt_claim_1_name varchar(128),
	asmt_claim_2_name varchar(128),
	asmt_claim_3_name varchar(128),
	asmt_claim_4_name varchar(128),
	asmt_perf_lvl_name_1 varchar(25),
	asmt_perf_lvl_name_2 varchar(25),
	asmt_perf_lvl_name_3 varchar(25),
	asmt_perf_lvl_name_4 varchar(25),
	asmt_perf_lvl_name_5 varchar(25),
	asmt_claim_perf_lvl_name_1 varchar(128),
	asmt_claim_perf_lvl_name_2 varchar(128),
	asmt_claim_perf_lvl_name_3 varchar(128),
	asmt_score_min int NOT NULL,
	asmt_score_max int NOT NULL,
	asmt_claim_1_score_min int NOT NULL,
	asmt_claim_1_score_max int NOT NULL,
	asmt_claim_2_score_min int NOT NULL,
	asmt_claim_2_score_max int NOT NULL,
	asmt_claim_3_score_min int NOT NULL,
	asmt_claim_3_score_max int NOT NULL,
	asmt_claim_4_score_min int,
	asmt_claim_4_score_max int,
	asmt_cut_point_1 int,
	asmt_cut_point_2 int,
	asmt_cut_point_3 int,
	asmt_cut_point_4 int,
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(1) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	PRIMARY KEY (asmt_rec_id)
);
CREATE TABLE dim_inst_hier (
	inst_hier_rec_id bigint NOT NULL,
	state_code varchar(2) NOT NULL,
	district_id varchar(40) NOT NULL,
	district_name varchar(60) NOT NULL,
	school_id varchar(40) NOT NULL,
	school_name varchar(60) NOT NULL,
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(1) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	PRIMARY KEY (inst_hier_rec_id)
);
CREATE TABLE dim_student (
	student_rec_id bigint NOT NULL,
	student_id varchar(40) NOT NULL,
	external_student_id varchar(40),
	first_name varchar(35),
	middle_name varchar(35),
	last_name varchar(35),
	birthdate varchar(8),
	sex varchar(10) NOT NULL,
	group_1_id varchar(40),
	group_1_text varchar(60),
	group_2_id varchar(40),
	group_2_text varchar(60),
	group_3_id varchar(40),
	group_3_text varchar(60),
	group_4_id varchar(40),
	group_4_text varchar(60),
	group_5_id varchar(40),
	group_5_text varchar(60),
	group_6_id varchar(40),
	group_6_text varchar(60),
	group_7_id varchar(40),
	group_7_text varchar(60),
	group_8_id varchar(40),
	group_8_text varchar(60),
	group_9_id varchar(40),
	group_9_text varchar(60),
	group_10_id varchar(40),
	group_10_text varchar(60),
	dmg_eth_derived int,
	dmg_eth_hsp varchar(5),
	dmg_eth_ami varchar(5),
	dmg_eth_asn varchar(5),
	dmg_eth_blk varchar(5),
	dmg_eth_pcf varchar(5),
	dmg_eth_wht varchar(5),
	dmg_eth_2om varchar(5),
	dmg_prg_iep varchar(5),
	dmg_prg_lep varchar(5),
	dmg_prg_504 varchar(5),
	dmg_sts_ecd varchar(5),
	dmg_sts_mig varchar(5),
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(1) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	PRIMARY KEY (student_rec_id)
);
CREATE TABLE fact_asmt_outcome (
	asmt_outcome_rec_id bigint NOT NULL,
	asmt_rec_id bigint NOT NULL,
	student_rec_id bigint NOT NULL,
	inst_hier_rec_id bigint NOT NULL,
	asmt_guid varchar(255) NOT NULL,
	student_id varchar(40) NOT NULL,
	state_code varchar(2) NOT NULL,
	district_id varchar(40) NOT NULL,
	school_id varchar(40) NOT NULL,
	where_taken_id varchar(40),
	where_taken_name varchar(60),
	asmt_grade varchar(10) NOT NULL,
	enrl_grade varchar(10) NOT NULL,
	date_taken varchar(8) NOT NULL,
	date_taken_day int NOT NULL,
	date_taken_month int NOT NULL,
	date_taken_year int NOT NULL,
	asmt_score int NOT NULL,
	asmt_score_range_min int NOT NULL,
	asmt_score_range_max int NOT NULL,
	asmt_perf_lvl int NOT NULL,
	asmt_claim_1_score int,
	asmt_claim_1_score_range_min int,
	asmt_claim_1_score_range_max int,
	asmt_claim_1_perf_lvl int,
	asmt_claim_2_score int,
	asmt_claim_2_score_range_min int,
	asmt_claim_2_score_range_max int,
	asmt_claim_2_perf_lvl int,
	asmt_claim_3_score int,
	asmt_claim_3_score_range_min int,
	asmt_claim_3_score_range_max int,
	asmt_claim_3_perf_lvl int,
	asmt_claim_4_score int,
	asmt_claim_4_score_range_min int,
	asmt_claim_4_score_range_max int,
	asmt_claim_4_perf_lvl int,
	acc_asl_video_embed int NOT NULL,
	acc_braile_embed int NOT NULL,
	acc_closed_captioning_embed int NOT NULL,
	acc_text_to_speech_embed int NOT NULL,
	acc_abacus_nonembed int NOT NULL,
	acc_alternate_response_options_nonembed int NOT NULL,
	acc_calculator_nonembed int NOT NULL,
	acc_multiplication_table_nonembed int NOT NULL,
	acc_print_on_demand_nonembed int NOT NULL,
	acc_print_on_demand_items_nonembed int NOT NULL,
	acc_read_aloud_nonembed int NOT NULL,
	acc_scribe_nonembed int NOT NULL,
	acc_speech_to_text_nonembed int NOT NULL,
	acc_streamline_mode int NOT NULL,
	acc_noise_buffer_nonembed int NOT NULL,
	complete varchar(5),
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(2) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	administration_condition varchar(2),
	PRIMARY KEY (asmt_outcome_rec_id)
);
CREATE TABLE fact_asmt_outcome_vw (
	asmt_outcome_vw_rec_id bigint NOT NULL,
	asmt_rec_id bigint NOT NULL,
	student_rec_id bigint NOT NULL,
	inst_hier_rec_id bigint NOT NULL,
	asmt_guid varchar(255) NOT NULL,
	student_id varchar(40) NOT NULL,
	state_code varchar(2) NOT NULL,
	district_id varchar(40) NOT NULL,
	school_id varchar(40) NOT NULL,
	where_taken_id varchar(40),
	where_taken_name varchar(60),
	asmt_type varchar(32) NOT NULL,
	asmt_year int NOT NULL,
	asmt_subject varchar(64) NOT NULL,
	asmt_grade varchar(10) NOT NULL,
	enrl_grade varchar(10) NOT NULL,
	date_taken varchar(8) NOT NULL,
	date_taken_day int NOT NULL,
	date_taken_month int NOT NULL,
	date_taken_year int NOT NULL,
	asmt_score int NOT NULL,
	asmt_score_range_min int NOT NULL,
	asmt_score_range_max int NOT NULL,
	asmt_perf_lvl int NOT NULL,
	asmt_claim_1_score int,
	asmt_claim_1_score_range_min int,
	asmt_claim_1_score_range_max int,
	asmt_claim_1_perf_lvl int,
	asmt_claim_2_score int,
	asmt_claim_2_score_range_min int,
	asmt_claim_2_score_range_max int,
	asmt_claim_2_perf_lvl int,
	asmt_claim_3_score int,
	asmt_claim_3_score_range_min int,
	asmt_claim_3_score_range_max int,
	asmt_claim_3_perf_lvl int,
	asmt_claim_4_score int,
	asmt_claim_4_score_range_min int,
	asmt_claim_4_score_range_max int,
	asmt_claim_4_perf_lvl int,
	sex varchar(10) NOT NULL,
	dmg_eth_derived int,
	dmg_eth_hsp varchar(5),
	dmg_eth_ami varchar(5),
	dmg_eth_asn varchar(5),
	dmg_eth_blk varchar(5),
	dmg_eth_pcf varchar(5),
	dmg_eth_wht varchar(5),
	dmg_eth_2om varchar(5),
	dmg_prg_iep varchar(5),
	dmg_prg_lep varchar(5),
	dmg_prg_504 varchar(5),
	dmg_sts_ecd varchar(5),
	dmg_sts_mig varchar(5),
	acc_asl_video_embed int NOT NULL,
	acc_braile_embed int NOT NULL,
	acc_closed_captioning_embed int NOT NULL,
	acc_text_to_speech_embed int NOT NULL,
	acc_abacus_nonembed int NOT NULL,
	acc_alternate_response_options_nonembed int NOT NULL,
	acc_calculator_nonembed int NOT NULL,
	acc_multiplication_table_nonembed int NOT NULL,
	acc_print_on_demand_nonembed int NOT NULL,
	acc_print_on_demand_items_nonembed int NOT NULL,
	acc_read_aloud_nonembed int NOT NULL,
	acc_scribe_nonembed int NOT NULL,
	acc_speech_to_text_nonembed int NOT NULL,
	acc_streamline_mode int NOT NULL,
	acc_noise_buffer_nonembed int NOT NULL,
	complete varchar(5),
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(1) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	administration_condition varchar(2),
	PRIMARY KEY (asmt_outcome_vw_rec_id)
);
CREATE TABLE fact_block_asmt_outcome (
	asmt_outcome_rec_id bigint NOT NULL,
	asmt_rec_id bigint NOT NULL,
	student_rec_id bigint NOT NULL,
	inst_hier_rec_id bigint NOT NULL,
	asmt_guid varchar(255) NOT NULL,
	student_id varchar(40) NOT NULL,
	state_code varchar(2) NOT NULL,
	district_id varchar(40) NOT NULL,
	school_id varchar(40) NOT NULL,
	where_taken_id varchar(40),
	where_taken_name varchar(60),
	asmt_type varchar(32) NOT NULL,
	asmt_year int NOT NULL,
	asmt_subject varchar(64) NOT NULL,
	asmt_grade varchar(10) NOT NULL,
	enrl_grade varchar(10) NOT NULL,
	date_taken varchar(8) NOT NULL,
	date_taken_day int NOT NULL,
	date_taken_month int NOT NULL,
	date_taken_year int NOT NULL,
	asmt_claim_1_score int,
	asmt_claim_1_score_range_min int,
	asmt_claim_1_score_range_max int,
	asmt_claim_1_perf_lvl int,
	sex varchar(10) NOT NULL,
	dmg_eth_derived int,
	dmg_eth_hsp varchar(5),
	dmg_eth_ami varchar(5),
	dmg_eth_asn varchar(5),
	dmg_eth_blk varchar(5),
	dmg_eth_pcf varchar(5),
	dmg_eth_wht varchar(5),
	dmg_eth_2om varchar(5),
	dmg_prg_iep varchar(5),
	dmg_prg_lep varchar(5),
	dmg_prg_504 varchar(5),
	dmg_sts_ecd varchar(5),
	dmg_sts_mig varchar(5),
	acc_asl_video_embed int NOT NULL,
	acc_braile_embed int NOT NULL,
	acc_closed_captioning_embed int NOT NULL,
	acc_text_to_speech_embed int NOT NULL,
	acc_abacus_nonembed int NOT NULL,
	acc_alternate_response_options_nonembed int NOT NULL,
	acc_calculator_nonembed int NOT NULL,
	acc_multiplication_table_nonembed int NOT NULL,
	acc_print_on_demand_nonembed int NOT NULL,
	acc_print_on_demand_items_nonembed int NOT NULL,
	acc_read_aloud_nonembed int NOT NULL,
	acc_scribe_nonembed int NOT NULL,
	acc_speech_to_text_nonembed int NOT NULL,
	acc_streamline_mode int NOT NULL,
	acc_noise_buffer_nonembed int NOT NULL,
	complete varchar(5),
	from_date varchar(8) NOT NULL,
	to_date varchar(8),
	rec_status varchar(1) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	administration_condition varchar(2),
	PRIMARY KEY (asmt_outcome_rec_id)
);
CREATE TABLE student_reg (
	student_reg_rec_id bigint NOT NULL,
	state_code varchar(2) NOT NULL,
	state_name varchar(50) NOT NULL,
	district_id varchar(40) NOT NULL,
	district_name varchar(60) NOT NULL,
	school_id varchar(40) NOT NULL,
	school_name varchar(60) NOT NULL,
	student_id varchar(40) NOT NULL,
	external_student_ssid varchar(40) NOT NULL,
	first_name varchar(35),
	middle_name varchar(35),
	last_name varchar(35),
	birthdate varchar(10),
	sex varchar(10) NOT NULL,
	enrl_grade varchar(10) NOT NULL,
	dmg_eth_hsp varchar(5),
	dmg_eth_ami varchar(5),
	dmg_eth_asn varchar(5),
	dmg_eth_blk varchar(5),
	dmg_eth_pcf varchar(5),
	dmg_eth_wht varchar(5),
	dmg_multi_race varchar(5),
	dmg_prg_iep varchar(5),
	dmg_prg_lep varchar(5),
	dmg_prg_504 varchar(5),
	dmg_sts_ecd varchar(5),
	dmg_sts_mig varchar(5),
	confirm_code varchar(50),
	language_code varchar(3),
	eng_prof_lvl varchar(20),
	us_school_entry_date varchar(10),
	lep_entry_date varchar(10),
	lep_exit_date varchar(10),
	t3_program_type varchar(27),
	prim_disability_type varchar(3),
	student_reg_guid varchar(50) NOT NULL,
	academic_year int NOT NULL,
	extract_date varchar(10) NOT NULL,
	reg_system_id varchar(40) NOT NULL,
	batch_guid varchar(36) NOT NULL,
	PRIMARY KEY (student_reg_rec_id)
);
ALTER TABLE fact_asmt_outcome
	ADD FOREIGN KEY (asmt_rec_id) 
	REFERENCES dim_asmt (asmt_rec_id);

ALTER TABLE fact_asmt_outcome
	ADD FOREIGN KEY (inst_hier_rec_id) 
	REFERENCES dim_inst_hier (inst_hier_rec_id);

ALTER TABLE fact_asmt_outcome
	ADD FOREIGN KEY (student_rec_id) 
	REFERENCES dim_student (student_rec_id);


ALTER TABLE fact_asmt_outcome_vw
	ADD FOREIGN KEY (asmt_rec_id) 
	REFERENCES dim_asmt (asmt_rec_id);

ALTER TABLE fact_asmt_outcome_vw
	ADD FOREIGN KEY (inst_hier_rec_id) 
	REFERENCES dim_inst_hier (inst_hier_rec_id);

ALTER TABLE fact_asmt_outcome_vw
	ADD FOREIGN KEY (student_rec_id) 
	REFERENCES dim_student (student_rec_id);


ALTER TABLE fact_block_asmt_outcome
	ADD FOREIGN KEY (asmt_rec_id) 
	REFERENCES dim_asmt (asmt_rec_id);

ALTER TABLE fact_block_asmt_outcome
	ADD FOREIGN KEY (inst_hier_rec_id) 
	REFERENCES dim_inst_hier (inst_hier_rec_id);

ALTER TABLE fact_block_asmt_outcome
	ADD FOREIGN KEY (student_rec_id) 
	REFERENCES dim_student (student_rec_id);


