-- This script applies preferred labels to all assessments. The label values are provided by SBAC.
--
-- This should be run *after* all assessment packages are loaded from ART.

use warehouse;

INSERT INTO import (status, content, contentType, digest) VALUES
  (0, 2, 'text/plain', 'assessment labels');
SELECT LAST_INSERT_ID() INTO @importid;

UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-BriefWrites-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-Editing-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-LangVocab-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-ListenInterpet-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA Performance Task - How We Learn (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-Perf-Explanatory-Marshmallow';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-ReadInfo-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-ReadLit-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-Research-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-Revision-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Algebra and Functions I (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-AlgLin';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Algebra and Functions II (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-AlgQuad';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Geometry Congruence (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-GCO-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Geometry and Right Triangle Trigonometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-GeoRightTriRatios-Calc-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Geometry Measurement and Modeling (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-GMD-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Interpreting Functions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-IF';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Number and Quantity (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-NQ';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math Performance Task - Teen Driving Restrictions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-Perf-TeenDrivingRest-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Statistics and Probability (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-SP-Calc-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Seeing Structure in Expressions/Polynomial Expressions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-SSE';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-BriefWrites-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-Editing-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-LangVocab-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-ListenInterpet-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA Performance Task - Beetles (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-Perf-Opinion-Beetles';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-ReadInfo-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-ReadLit-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-Research-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-Revision-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-G-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math - Measurement and Data (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-MD-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math - Number and Operations in Base Ten (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-NBT-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math - Number and Operations - Fractions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-NF-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math - Operations and Algebraic Thinking (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-OA-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math Performance Task - Order Form (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3M-Perf-OrderForm-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-BriefWrites-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-Editing-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-LangVocab-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-ListenInterpet-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA Performance Task - Unlikely Animal Friends (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-Perf-Narrative-UnlikelyAnimal';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-ReadInfo-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-ReadLit-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-Research-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-Revision-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-G-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math - Measurement and Data (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-MD-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math - Number and Operations in Base Ten (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-NBT-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math - Number and Operations - Fractions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-NF-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math - Operations and Algebraic Thinking (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-OA-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math Performance Task - Animal Jumping (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4M-Perf-AnimalJumping-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-BriefWrites-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-Editing-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-LangVocab-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-ListenInterpet-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA Performance Task - Whales (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-Perf-Narrative-Whales';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Read Informational Texts  (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-ReadInfo-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-ReadLit-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-Research-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-Revision-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-G-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math - Measurement and Data (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-MD-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math - Number and Operations in Base Ten (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-NBT-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math - Number and Operations - Fractions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-NF-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math - Operations and Algebraic Thinking (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-OA-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math Performance Task - Turtle Habitat (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5M-Perf-TurtleHabitat-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-BriefWrites-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-Editing-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-LangVocab-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-ListenInterpet-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA Performance Task - Multivitamins (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-Perf-Argument-Multivitamins';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-ReadInfo-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-ReadLit-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-Research-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-Revision-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math - Expressions and Equations (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-EE';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-G-Calc-MATH-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math - The Number System (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-NS';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math Performance Task - Cell Phone Plan (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-Perf-CellPhonePlan-MATH-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math - Ratios and Proportional Relationships (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-RP';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math - Statistics and Probability (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6M-SP';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-BriefWrites-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Editing (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-Editing-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Language and Vocabulary Use (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-LangVocab-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-ListenInterpet-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA Performance Task - Mobile Ed Technology (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-Perf-Explanatory-MobileEdTech';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-ReadInfo-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-ReadLit-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-Research-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Revision (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-Revision-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math - Expressions and Equations (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-EE';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-G';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math - The Number System (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-NS';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math Performance Task - Camping Tasks (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-Perf-CampingTasks-MATH-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math - Ratios and Proportional Relationships (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-RP-Calc-MATH-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math - Statistics and Probability (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7M-SP-Calc-MATH-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Brief Writes (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-BriefWrites-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-EditRevise-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Listen/Interpret (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-ListenInterpet-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Performance Task - Compare Ancient Societies (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-Perf-Explanatory-CompareAncient';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Read Informational Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-ReadInfo-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Read Literary Texts (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-ReadLit-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA - Research (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-Research-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math - Expressions and Equations I (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-EE';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math - Expressions and Equations II (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-EE2-Calc-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math - Functions (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-F-Calc-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math - Geometry (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-G-Calc-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math - The Number System (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-NS-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math Performance Task - Baseball Tickets (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8M-Perf-BaseballTickets-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'Student Help for Math IAB' WHERE name = 'SH-SBAC-IAB-Math-Student Help-11';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11E-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11M-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3E-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA Performance Task - Beetles (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3E-Perf-AnimalsWithShells';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3M-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math Performance Task - Order Form (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3M-Perf-OrderForm-MATH-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4E-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA Performance Task - Unlikely Animal Friends (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4E-Perf-UncommonAnimals';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4M-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math Performance Task - Animal Jumping (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4M-Perf-AnimalJumping-MATH-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5E-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA Performance Task - Whales (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5E-Perf-MarineAnimal';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5M-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math Performance Task - Turtle Habitat (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5M-Perf-TurtleHabitat-MATH-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6E-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA Performance Task - Multivitamins (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6E-Perf-ImportanceOfNutrition';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6M';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math Performance Task - Cell Phone Plan (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6M-Perf-CellPhonePlan-MATH-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7E-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA Performance Task - Mobile Ed Technology (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7E-Perf-TechnologyInTheClassroom';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7M';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math Performance Task - Camping Tasks (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7M-Perf-CampingTasks-MATH-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8E-ELA-8';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Performance Task - Compare Ancient Societies (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8E-Perf-CompareAncientSoc';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8M';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math Performance Task - Baseball Tickets (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8M-Perf-BaseballTickets-MATH-8';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11E-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA Performance Task - How We Learn (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11E-Perf-HowWeLearn';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math Interim Test (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11M';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math Performance Task - Teen Driving Restrictions (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11M-Perf-TeenDrivingRestricitons-MATH-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11E-EditRevise-ELA-11';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Algebra and Functions I (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-AlgLinearFun';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math - Algebra and Functions II (IAB)' WHERE name = 'SBAC-IAB-FIXED-G11M-AlgQuadFun';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G3E-EditRevise-ELA-3';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G4E-EditRevise-ELA-4';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G5E-EditRevise-ELA-5';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G6E-EditRevise-ELA-6';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA - Edit/Revise (IAB)' WHERE name = 'SBAC-IAB-FIXED-G7E-EditRevise-ELA-7';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Performance Task - Preserve or Present (IAB)' WHERE name = 'SBAC-IAB-FIXED-G8E-Perf-Argument-PreserveOrPresent';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G11-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G11-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G3-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G3-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G4-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G4-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G5-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G5-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G6-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G6-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G7-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G7-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 ELA' WHERE name = 'SBAC-IAB-G8-ELA-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'Grades 3 - 12 MATH' WHERE name = 'SBAC-IAB-G8-Math-COMBINED';
UPDATE asmt SET update_import_id = @importid, label = 'High School ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'High School Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G11M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 03 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G3M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 04 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G4M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 05 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G5M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 06 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G6M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 07 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G7M-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 ELA Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8E-COMBINED-2017';
UPDATE asmt SET update_import_id = @importid, label = 'Grade 08 Math Interim Comprehensive (ICA)' WHERE name = 'SBAC-ICA-FIXED-G8M-COMBINED-2017';

UPDATE import SET status = 1 WHERE id = @importid;